### ISSUE TITLE
Thank you for the dataset

### ISSUE THREAD

**Issue by asigalov61** [music-x-lab/POP909-Dataset#5]
Hey music-x-lab team,

Just wanted to share with you a few MIDI samples generated with your dataset. I think you may find it interesting.

[POP909GeneratedSamples.zip](https://github.com/music-x-lab/POP909-Dataset/files/6091087/POP909GeneratedSamples.zip)

This was made with GPT2 implementation + custom MIDI processors.
https://github.com/asigalov61/Optimus-VIRTUOSO/blob/main/Optimus_VIRTUOSO.ipynb

I like the results and I will continue exploring what your dataset has to offer.

Thank you.

**Comment by RetroCirce** [comment]
Thank you for your consideration and appreciation of our dataset!!

**Comment by asigalov61** [comment]
Yes, you are very welcome! :)

I am getting fantastic results with it and I wanted to provide you with a longer output sample so that you can see how well it performs.

Thank you very much!
[POP909-Long-Output-Sample.zip](https://github.com/music-x-lab/POP909-Dataset/files/6330187/POP909-Long-Output-Sample.zip)

https://soundcloud.com/aleksandr-sigalov-61/ov-sample-4-20210417170114-aac/s-y2qq9DfuI3A

Most Sincerely,

Alex
