### ISSUE TITLE
About the original audio files

### ISSUE THREAD

**Issue by RMSnow** [music-x-lab/POP909-Dataset#6]
Hi, I'm greatly admiring and grateful for the quality of the dataset and your team's efforts behind it. 

I wonder to know how can I access the original audio data? In the Index File, you list the song name and the artist. So only I can do is to search the audio on some music apps?

**Comment by RetroCirce** [comment]
Sorry for the late reply!
Yes, because of the copyright issue, we cannot release the audio files. The only way to can do is to search for each song name and get the song from online platform, if you have right to download those files in legal.
