### ISSUE TITLE
question about MELODY

### ISSUE THREAD

**Issue by LqNoob** [music-x-lab/POP909-Dataset#7]
Hi, @RetroCirce. Thank you for your great work. 
I have a question about "MELODY: the lead (vocal) melody transcription" described in 3.2 in the paper. How do you extract the lead (vocal) melody of the music. And how do you do vocal melody transcription when there are vocals in the music. 
Thank you.

**Comment by RetroCirce** [comment]
Hi, as mentioned in our paper. Pop909’s vocal melody is extracted by human. We hire musicians and composers to give the expert label for the melody.
